### ISSUE TITLE
Fails for country specific TLDs

### ISSUE THREAD

**Issue by eduardocereto** [websanova/js-url#3]
```javascript

$.url('host', 'http://www.google.com.br')
> "com.br"
$.url('sub', 'http://www.google.com.br')
> "www.google"
$.url('tld', 'http://www.google.com.br')
> "br"
```

**Comment by ssreekanth** [comment]
@websanova, are you planning to handle this issue? do you care to integrate your library with tld.js or publicsuffixlist.js (from the earlier comments), they both handle the country specific tlds? Thanks for the wonderful url parser library..

**Comment by websanova** [comment]
I'm currently preoccupied with work and a side project now so don't have
too much time to look into it. However would be good to make it some kind
of optional include if anyone is interested in integrating.

**Comment by websanova** [comment]
Added support for this. Comes in two versions now `url-tld.min.js` and `url.min.js`. The tld version is about twice the size since it contains a hard coded list of tld's. Not sure if it contains all of them, as I just copy and paste this off stackoverflow. Let me know if any are missing and I will add them.
