### ISSUE TITLE
url.min.js BUG

### ISSUE THREAD

**Issue by hgati** [websanova/js-url#38]
there is  a bug on your url.min.js 
url('domain') not work (undefined)
the url.js works but url.min.js not work.

**Comment by websanova** [comment]
Hey, which version are you using?

The latest seems ok for me.

Also is this just the test file already in there or some custom test and url?

**Comment by hgati** [comment]
that version is..
https://raw.githubusercontent.com/websanova/js-url/master/url.min.js

**Comment by websanova** [comment]
Can you post an example html file?

**Comment by websanova** [comment]
Are you still having issues with this in the new version?

**Comment by hgati** [comment]
yes i'll try to test.

**Comment by hgati** [comment]
Yes, same to.
still "undefined"

here is test url
http://dev.voabox.com/test.html

**Comment by websanova** [comment]
What happens if you run it like `url('domain', 'http://amarket.co.kr');` Also can you check what `window.location.toString()` gives you please.

**Comment by websanova** [comment]
Hey, sorry, just realized. You need to use the `url-tld` version to get the domain. This is because it includes a list of tld names such as co.kr which is required to parse out what the correct domain, tld and sub domains are.

Use this one: https://raw.githubusercontent.com/websanova/js-url/master/url-tld.min.js

**Comment by hgati** [comment]
Great~
It works. thanks.
