### ISSUE TITLE
url('file') is undefined with url end with no extension

### ISSUE THREAD

**Issue by horans** [websanova/js-url#42]
version: 2.0.2

#### case 1, end with no extension or forward slash:
	var urlString = http://localhost/news/list
	window.url('file', urlString): undefined		//should be "list"
	window.url('filename', urlString): undefined	//should be "list"
	window.url('-1', urlString): list

#### case 2, end with dot, no extension:
	var urlString = http://localhost/news/list.
	window.url('file', urlString): undefined		//should be "list."
	window.url('filename', urlString): undefined	//should be "list"
	window.url('-1', urlString): list.

#### case 3, end with forward slash:
	var urlString = http://localhost/news/list/
	window.url('file', urlString): undefined
	window.url('filename', urlString): undefined
	window.url('-1', urlString): list				//should be ""

#### case 4, regular:
	var urlString = http://localhost/news/list.html
	window.url('file', urlString): list.html
	window.url('filename', urlString): list
	window.url('-1', urlString): list.html

**Comment by websanova** [comment]
This is intended behavior in all cases. Particularly with just a `/something` path. Actually a system has no idea really whether "you" mean path/directory or file.

You could perhaps do:

```
var file = window.url('file', urlString) || window.url('-1', urlString);
```

Or you can fetch the entire parsed url with:

```
window.url('[]', urlString);
```

**Comment by horans** [comment]
when a url end with forward slash, it's usually a path/directory, which the file name is hidden/omitted, such as "index.html"; while a url end with file name without extension, it‘s usually because the rewrite rule.

in my case, i need to use [History.pushState()](https://developer.mozilla.org/docs/Web/API/History/pushState) to change the url query strings.
for example, change "http://localhost/news/list" into "http://localhost/news/list?type=1", and "http://localhost/news/list/" into "http://localhost/news/list/?type=1". so i have to discriminate these two situations.

in the "http://localhost/news/list/" case, `window.url('-1', urlString)` is giving "list", rather than "list/". than with `var file = window.url('file', urlString) || window.url('-1', urlString);`, it will finally turn into "http://localhost/news/list/list?type=1" :(

i haven't found `window.url('[]', urlString);` in readme, test it later. (is it similar to `window.url('', urlString);`, but store values in a array?)

**Comment by websanova** [comment]
Seems the issue is more about `/list/` returning `''` rather than `list`. But this was a conscious decision. I'm not sure about specific RFC's, but generally I see that if you have a route `/list` and `/list/` they will serve the same request. Furthermore `/list/` will return `null` if you try to do some kind of `...segment(2)` call. We can also add that most webservers will strip the forward slash if nothing comes after it.

On a side note, on unix based systems you can not have a file and a directory with the same name at the same level. However on Windows you can so I guess there is some arguing.

However if the forward slash were to be implemented, then it would follow that `/list/` would return `''` (empty string) for `-1` and not `list/`.

I think it's probably best to avoid having "files" and "directories" with the same name. Which would pretty much remove the issue altogether.

**Comment by horans** [comment]
i agree it is a "conscious decision". and yes, the problem is caused by a .net project on windows. i wasn't aware it until our back-end engineer told me.

never mind, i replaced it with native `window.location.pathname` witch will give the both ".../list" and ".../list/".
